### PR TITLE
Added isPassive() and isForceAuthn() to AuthnRequest

### PR DESCRIPTION
**Pull request by elzekool**
Hi,

I'm working on an IdP and I need isPassive and forceAuthn. I think anyone using this bundle as an IdP needs them.

### CODE REVIEW

**Comment by DRvanR** [comment]
Hello!

first of all, thanks for the patch! Do you think you could add tests for it that it can be read when creating a new AuthnRequest from XML akin to https://github.com/SURFnet/Stepup-saml-bundle/blob/6276e60a5acd2883bfb5a1d51dbe2caa49ad79f7/src/Tests/SAML2/AuthnRequestTest.php#L96-L105?

**Comment by elzekool** [comment]
Hi Daan,

Of course, I added a new commit to the PR

**Comment by DRvanR** [comment]
Thanks @elzekool!

**Comment by DRvanR** [comment]
These changes have been released as part of [version 2.3.0][1]

[1]: https://github.com/SURFnet/Stepup-saml-bundle/releases/tag/2.3.0

**Pull request merged**
